version: "3.6"
services:
  db:
    image: postgres:13.2
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready-U postgres"]
      timeout: 10s
      interval: 5s
      retries: 15
    restart: always
    env_file:
      - config.env
    networks:
      - internal
  service_1:
    container_name: service_1
    build: .
    env_file:
      - config.env
    depends_on:
      - db
    networks:
      - internal
      - external
  service_2:
    container_name: service_2
    build: .
    env_file:
      - config.env
    depends_on:
      - db
    networks:
      - internal
      - external
    command: "cargo run --release"
  lb:
    container_name: lb
    image: nginx:alpine
    ports:
      - 8000:8000
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - service_1
      - service_2
    networks:
      - internal
      - external
    command: [nginx-debug, "-g", "daemon off;"]
  frontend:
    container_name: frontend
    build: ../Front-end
    networks:
      - internal

networks:
  external:
  internal:
    internal: true