version: '3.6'
services:
  db:
    image: postgres:latest
    container_name: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready-U postgres" ]
      timeout: 10s
      interval: 5s
      retries: 15
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qr_slip
    ports: 
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - internal
  service:
    #container_name: qr_slip
    build: .
    environment: 
      JWT_SECRET: 165434867894
      DATABASE_URL: postgres://postgres:password@db:5432/qr_slip
    ports: 
      - 8000:8000
    depends_on:
      - db
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 2
  lb:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes: 
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    depends_on: 
      - service
    networks:
      - internal
      - external
    command: [nginx-debug, '-g', 'daemon off;']

networks:
  external:
  internal:
    internal: true





  # service_1:
  #     #container_name: qr_slip
  #   build: .
  #   environment: 
  #     JWT_SECRET: 165434867894
  #     DATABASE_URL: postgres://postgres:password@db:5432/qr_slip
  #   ports: 
  #     - 80:8000
  #   depends_on:
  #     - db
  #   networks:
  #     - internal
  # service_2:
  #       #container_name: qr_slip
  #   build: .
  #   environment: 
  #     JWT_SECRET: 165434867894
  #     DATABASE_URL: postgres://postgres:password@db:5432/qr_slip
  #   ports: 
  #     - 81:8000
  #   depends_on:
  #     - db
  #   networks:
  #     - internal