version: '3.6'
services:
  db:
    image: postgres:latest
    container_name: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready-U postgres" ]
      timeout: 10s
      interval: 5s
      retries: 15
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qr_slip
    ports: 
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  qr_slip:
    container_name: qr_slip
    build: .
    environment: 
      JWT_SECRET: 165434867894
      DATABASE_URL: postgres://postgres:password@db:5432/qr_slip
    ports: 
      - 127.0.0.1:80:8000
    depends_on:
      - db